"""fix devices

Revision ID: 308aaadc573a
Revises: 6d7b701f6388
Create Date: 2023-06-16 17:36:14.262108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308aaadc573a'
down_revision = '6d7b701f6388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('devices_drivers_id_fkey', 'devices', type_='foreignkey')
    op.drop_column('devices', 'drivers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('drivers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('devices_drivers_id_fkey', 'devices', 'drivers', ['drivers_id'], ['id'])
    # ### end Alembic commands ###
