"""create db

Revision ID: 5222f0023313
Revises: 5af34b64968c
Create Date: 2023-06-14 11:24:12.833601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5222f0023313'
down_revision = '5af34b64968c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
