"""fix rmk

Revision ID: 674b5fba6340
Revises: 9130792668de
Create Date: 2023-06-17 18:08:11.332994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674b5fba6340'
down_revision = '9130792668de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rmk_store_id_fkey', 'rmk', type_='foreignkey')
    op.drop_column('rmk', 'store_id')
    op.add_column('store', sa.Column('rmk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'store', 'rmk', ['rmk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store', type_='foreignkey')
    op.drop_column('store', 'rmk_id')
    op.add_column('rmk', sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('rmk_store_id_fkey', 'rmk', 'store', ['store_id'], ['id'])
    # ### end Alembic commands ###
