"""add driver.is in devices

Revision ID: 6d7b701f6388
Revises: d0810b5ae8d8
Create Date: 2023-06-16 12:59:37.080988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7b701f6388'
down_revision = 'd0810b5ae8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('drivers_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'drivers', ['drivers_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'drivers_id')
    # ### end Alembic commands ###
