"""create db

Revision ID: 6ce55d48d094
Revises: 
Create Date: 2023-06-14 13:20:38.546206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ce55d48d094'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position_save', sa.String(length=200), nullable=True),
    sa.Column('model_device', sa.String(length=200), nullable=True),
    sa.Column('type_device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_device_id'], ['type_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantity_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rmk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hide', sa.Boolean(), nullable=True),
    sa.Column('rmk_id', sa.Integer(), nullable=True),
    sa.Column('type_device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rmk_id'], ['rmk.id'], ),
    sa.ForeignKeyConstraint(['type_device_id'], ['type_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers_devices',
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers_devices')
    op.drop_table('devices')
    op.drop_table('rmk')
    op.drop_table('quantity_products')
    op.drop_table('drivers')
    op.drop_table('type_device')
    op.drop_table('store')
    op.drop_table('product')
    # ### end Alembic commands ###
