"""fix

Revision ID: a0700392a4a8
Revises: 
Create Date: 2023-06-09 18:16:05.142426

"""
,lkofrom alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0700392a4a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
